
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: 'false'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port : 13001

database:
  url: ${DATABASE_URL}

supply-api:
  url: "https://rethink-supplier.herokuapp.com"
  endpoints:
    order: "/order"
    orderline: "/orderline/"
    send-order: "/send_order"
    product: "/product/"
    delivery: "/delivery/"
  auth:
    username: ${SUPPLY_API_USERNAME}
    token: ${SUPPLY_API_TOKEN}

inventory-service:
  url: "http://localhost:13000"
  endpoints:
    lowstock: "/stock/low"